general.import = [
    "~/.config/alacritty/themes/themes/tokyo_night.toml"
]

[ env ]
TERM = "alacritty"

[window]
padding.x = 5
padding.y = 5
opacity = 0.95

decorations = "None"

[font]
normal.family = "MesloLGS Nerd Font Mono"

#regular
size = 11

#for video
# size = 35.0


